[package]
name = "toy-redis"
version = "0.1.2"
authors = ["Yiran Sheng <shengyiran@gmail.com>"]

[dependencies]
stringreader = "0.1.1"
matches = "0.1.6"

lazy_static = "1.0"
bytes = "0.4.6"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
